version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - revive
    - gocritic
    - bodyclose
    - nilerr
    - misspell

run:
  go: "1.22"
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
